language: php

## Run on sudo environment
sudo: required

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## List all PHP versions to test with
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

## Define all ENV vars to test with
env:
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"

# Install system packages
before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
  - sudo apt-get install -qq zip php5-zip php7.0-zip

## Install Dependencies
install:
  - composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer require laravel/framework:${LARAVEL_VERSION} --no-update --no-interaction
  - composer install --prefer-dist --no-interaction

## Run Scripts before Tests
before_script:
  - composer dump-autoload -o

## Run test Scripts
script:
  - vendor/bin/phpunit
#  - php CoverageChecker.php build/clover.xml 65

## Send Build Notifications to Slack
notifications:
  slack: gummibeer:7LQFrbHQqjl98ZvbD9nV8zHN
